---
default:
  image: jereortega24/demo-deployer:3

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

variables:
  KUBE_CONTEXT: jereortega24/gitlab-agents:demo

stages:
  - terraform
  - helm

eks:
  stage: terraform
  variables:
    TF_ROOT: eks
  trigger:
    include: .gitlab/ci/terraform.gitlab-ci.yml
  rules:
    - changes:
        - eks/**/*

route53:
  stage: terraform
  variables:
    TF_ROOT: route53
  trigger:
    include: .gitlab/ci/terraform.gitlab-ci.yml
  rules:
    - changes:
        - route53/**/*

vpc:
  stage: terraform
  variables:
    TF_ROOT: vpc
  trigger:
    include: .gitlab/ci/terraform.gitlab-ci.yml
  rules:
    - changes:
        - vpc/**/*

gitlab-agent:
  stage: helm
  script:
    - cd gitlab-agent/
    - version=2.0.0
    - kubectl config use-context "$KUBE_CONTEXT"
    - helm repo add gitlab https://charts.gitlab.io
    - helm upgrade --install -n demo --version $version -f values.yml gitlab-agent gitlab/gitlab-agent
  rules:
    - when: manual
      changes:
        - gitlab-agent/**/*

ingress-nginx:
  stage: helm
  script:
    - cd ingress-nginx/
    - version=4.10.1
    - kubectl config use-context "$KUBE_CONTEXT"
    - helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
    - helm upgrade --install -n demo --version $version -f values.yml ingress-nginx ingress-nginx/ingress-nginx
  rules:
    - when: manual
      changes:
        - ingress-nginx/**/*

postgresql:
  stage: helm
  script:
    - cd postgresql/
    - version=15.2.9
    - kubectl config use-context "$KUBE_CONTEXT"
    - helm upgrade --install -n demo --version $version -f values.yml postgresql oci://registry-1.docker.io/bitnamicharts/postgresql
  rules:
    - when: manual
      changes:
        - postgresql/**/*
