---
controller:
  config:
    enable-opentracing: 'true'
    proxy-body-size: 10m
    proxy-buffer-size: 12k
    proxy-buffers: 8 8k
  enableTopologyAwareRouting: true
  ingressClassResource:
    name: ingress-nginx
    enabled: true
    default: false
    controllerValue: k8s.io/ingress-nginx
  scope:
    enabled: true
    namespace: '' # defaults to $(POD_NAMESPACE)
  extraEnvs:
    - name: DD_AGENT_HOST
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.hostIP
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: environment
                operator: In
                values:
                  - demo
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          app.kubernetes.io/component: controller
          app.kubernetes.io/instance: ingress-nginx
  replicaCount: 3
  service:
    enabled: true
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: environment=demo,managed-by=eks
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tls
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
      service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-west-2:652725896823:certificate/7782e98d-f098-49d3-8736-2a247ea19cf6
      service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: ELBSecurityPolicy-TLS13-1-2-2021-06
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
    enableHttp: false
    enableHttps: true
    targetPorts:
      https: http
    type: LoadBalancer
  priorityClassName: system-cluster-critical
