---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "demo.fullname" . }}
  labels:
    {{- include "demo.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.config.data -}}
  {{$k | toYaml | nindent 2 }}: {{$v | toYaml }}
  {{- end }}
