{{- if .Values.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
{{- if .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4}}
{{- end }}
  labels:
    {{- include "demo.labels" . | nindent 4 }}
  name: {{ include "demo.serviceAccountName" . }}
{{- end }}
